language: php
php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - sudo apt-get install libgearman
  - yes | pecl install gearman
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
