language: php
php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - wget https://launchpad.net/gearmand/1.2/1.1.11/+download/gearmand-1.1.11.tar.gz
  - tar xf gearmand-1.1.11.tar.gzs
  - cd gearmand-1.1.11
  - ./configure
  - make
  - sudo make install
  - yes | pecl install gearman
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
